LIBRARIES += src/plugins/statetrans/libplugin_statetrans
libplugin_statetrans_MODULES := statetrans engine statemachine_tcp evaluator_chebyshev conversation packet_buffer

DOCS += src/plugins/statetrans
