UCOLLECT_PLUGINS:= \
	count \
	buckets \
	crash \
	badconf \
	sniff \
	bandwidth \
	flow \
	majordomo \
	cfgtest \
	spoof \
	refused \
	fake \
	plugtest \
	fwup \
	statetrans

include $(patsubst %,$(S)/src/plugins/%/Makefile.dir,$(UCOLLECT_PLUGINS))
